#Hosts

ha[0]=LA

hb[0]=LB

hc[0]=LC

hd[0]=LD

#Router
ra[0]=LA
ra[1]=F
ra[2]=I


rb[0]=LB
rb[1]=F
rb[2]=G
rb[3]=J


rc[0]=LC
rc[1]=I
rc[2]=H
rc[3]=L


rd[0]=LD
rd[1]=L
rd[2]=J


re[0]=H
re[1]=G
re[2]=K


