#Sucursal 1
r1[0]="LS1"
h_s1a[0]="LS1"
h_s1b[0]="LS1"

#Sucursal 5
r5[0]="LS5"
h_s5a[0]="LS5"
h_s5b[0]="LS5"

#Sucursal 7
r7[0]="LS7"
h_s7a[0]="LS7"
h_s7b[0]="LS7"

#Sucursal 2
r2[0]="LS2"
h_s2a[0]="LS2"
h_s2b[0]="LS2"

#Sucursal 6
r6[0]="LS6"
h_s6a[0]="LS6"
h_s6b[0]="LS6"

#Sucursal 8
r8[0]="LS8"
h_s8a[0]="LS8"
h_s8b[0]="LS8"

#Sucursal 3
r3[0]="LS3"
h_s3a[0]="LS3"
h_s3b[0]="LS3"

#Sucursal 4
r4[0]="LS4"
h_s4a[0]="LS4"
h_s4b[0]="LS4"
